/* Libros en euskera de Armiarma (armiarma.eus/liburu-e): [m, f, título, autor, género, año].
   m = kla (clásico vasco) o itz (traducción); f = nombre del fichero sin .epub.
   GENERADO por tools/build_armiarma.py; no editar a mano. */
window.ARMIARMA = [["kla","Juan Antonio Mogel, Peru Abarka","Peru Abarka","Juan Antonio Mogel","narratiba",1802],
["kla","Bizenta Mogel, Ipui onak","Ipui onak","Bizenta Mogel","narratiba",1804],
["kla","Jean Pierre Duvoisin, Telemake","Telemake","Jean Pierre Duvoisin","narratiba",1833],
["kla","Jean Baptiste Daskonagerre, Atheka gaitzeko oihartzunak","Atheka gaitzeko oihartzunak","Jean Baptiste Daskonagerre","narratiba",1870],
["kla","Wendworth Webster, Euskal ipuinak","Euskal ipuinak","Wentworth Webster","narratiba",1877],
["kla","Arturo Kanpion, Euskal lanak","Euskal lanak","Arturo Kanpion","narratiba",1878],
["kla","Alfonso Maria Zabala, Gabon gau bat","Gabon zar bat eta beste ipui asko","Alfonso Maria Zabala","narratiba",1880],
["kla","Gregorio Arrue, Santa Genobebaren bizitza","Santa Genobebaren bizitza","Gregorio Arrue","narratiba",1885],
["kla","Pedro Miguel Urruzuno, Ur-zale baten ipuiak","Ur-zale baten ipuiak","Pedro Migel Urruzuno","narratiba",1885],
["kla","Jean Baptiste Elizanburu, Piarres Adame","Piarres Adame","Jean Baptiste Elizanburu","narratiba",1889],
["kla","Antero Apaolaza, Patxiko Txerren","Patxiko Txerren","Antero Apaolaza","narratiba",1890],
["kla","Resurreccion M Azkue, Bein da betiko","Bein da betiko","Resurreccion Maria Azkue","narratiba",1890],
["kla","Resurreccion M Azkue, Batxi Guzur","Batxi Guzur","Resurreccion Maria Azkue","narratiba",1897],
["kla","Pedro Miguel Urruzuno, Sasiletrau baten ziria","Sasiletrau baten ziria, eta abar","Pedro Migel Urruzuno","narratiba",1897],
["kla","Domingo Agirre, Auñemendiko lorea","Auñemendiko lorea","Domingo Agirre","narratiba",1898],
["kla","Pedro Miguel Urruzuno, Euskalerritik zerura","Euskalerritik zerura eta beste ipui batzuk","Pedro Migel Urruzuno","narratiba",1898],
["kla","Domingo Agirre, Ioan-etorri bat Erromara","Ioan-etorri bat Erromara","Domingo Agirre","narratiba",1899],
["kla","JL Zutagape, Matxin mungiarra","Matxin mungiarra","J.L. Zutagape","narratiba",1899],
["kla","Pedro Miguel Urruzuno, Iru ziri","Iru ziri","Pedro Migel Urruzuno","narratiba",1899],
["kla","Domingo Agirre, Kresala","Kresala","Domingo Agirre","narratiba",1906],
["kla","Jose Manuel Etxeita, Josetxo","Josetxo","Jose Manuel Etxeita","narratiba",1909],
["kla","Jean Baptiste Constantin, Don Juan eta bere adixkidiak","Don Juan eta bere adixkidiak","Jean Baptiste Constantin","narratiba",1910],
["kla","Jose Manuel Etxeita, Jaioterri maitia","Jaioterri maitia","Jose Manuel Etxeita","narratiba",1910],
["kla","Domingo Agirre, Garoa","Garoa","Domingo Agirre","narratiba",1912],
["kla","Antonio Arruti, Lukainka","Lukainka","Antonio Arruti","narratiba",1913],
["kla","Bingen Aizkibel, Ipuin aberkoyak","Ipuin aberkoyak","Bingen Aizkibel","narratiba",1917],
["kla","Resurreccion M Azkue, Ardi galdua","Ardi galdua","Resurreccion Maria Azkue","narratiba",1918],
["kla","Kirikiño, Abarrak","Abarrak","Kirikiño","narratiba",1918],
["kla","Resurreccion Maria Azkue, Latsibi","Latsibi","Resurreccion Maria Azkue","narratiba",1920],
["kla","Zerbitzari, Artho-xuritzetan","Artho-xuritzetan","Zerbitzari","narratiba",1921],
["kla","Pierre Lhande, Yolanda","Yolanda","Pierre Lhande","narratiba",1921],
["kla","Bittor Garitaonandia, Ipuin laburrak","Ipuin laburrak","Bitor Garitaonandia","narratiba",1922],
["kla","Nemesio Etxaniz, Arraldea","Arraldea","Nemesio Etxaniz","narratiba",1923],
["kla","Jean Barbier, Supazter xokoan","Supazter xokoan","Jean Barbier","narratiba",1924],
["kla","Gregorio Mujika, Pernando Amezketarra","Pernando Amezketarra","Gregorio Mujika","narratiba",1925],
["kla","Jean Barbier, Piarres I","Piarres I","Jean Barbier","narratiba",1926],
["kla","Jean Baptiste Constantin, Haritxabalet","Haritxabalet Jaun apezaren gainen","Jean Baptiste Constantin","narratiba",1926],
["kla","Jean Barbier, Ixtorio-mixterio","Ixtorio-mixterio","Jean Barbier","narratiba",1929],
["kla","Jean Barbier, Piarres II","Piarres II","Jean Barbier","narratiba",1929],
["kla","Orixe, Tormesko itsu-mutila","Tormesko itsu-mutila","Orixe","narratiba",1929],
["kla","Paulo Zamarripa, Anayak gara","Anaiak gara","Paulo Zamarripa","narratiba",1929],
["kla","Orixe, Santa Kruz apaiza","Santa Kruz apaiza","Orixe","narratiba",1929],
["kla","Kirikiño, Bigarrengo abarrak","Bigarrengo abarrak","Kirikiño","narratiba",1930],
["kla","Orixe, Mireio","Mireio","Orixe","narratiba",1930],
["kla","Paulo Zamarripa, Kili-kili","Kili-kili","Paulo Zamarripa","narratiba",1930],
["kla","Augustin Anabitarte, Usauri","Usauri","Augustin Anabitarte","narratiba",1931],
["kla","Augustin Anabitarte, Donostia","Donostia","Augustin Anabitarte","narratiba",1932],
["kla","Mendi-Lauta, Loretxo","Loretxo","Mendi-Lauta","narratiba",1932],
["kla","Otxolua, Bertolda eta Bertoldin","Bertolda eta Bertoldin","Otxolua","narratiba",1932],
["kla","Barrensoro, Gazigozoak","Gazigozoak","Barrensoro","narratiba",1933],
["kla","Polikarpo Iraizoz, Lapurren menpean","Lapurren menpean","Polikarpo Iraizozkoa","narratiba",1935],
["kla","Paulo Zamarripa, Firi-firi","Firi-firi","Paulo Zamarripa","narratiba",1935],
["kla","Zerbitzari, Banhar","Banhar deitu salbaiak","Zerbitzari","narratiba",1936],
["kla","Barrensoro, Uztaro","Uztaro","Barrensoro","narratiba",1937],
["kla","Piarres Lafitte, Murtuts eta bertze","Murtuts eta bertze","Piarres Lafitte","narratiba",1945],
["kla","Jose Eizagirre, Ekaitzpean","Ekaitzpean","Jose Eizagirre","narratiba",1948],
["kla","Errose Bustintza, Euskalerriko ipuñak","Euskalerriko ipuñak","Errose Bustintza","narratiba",1950],
["kla","Jon Andoni Irazusta, Bizia garratza da","Bizia garratza da","Jon Andoni Irazusta","narratiba",1950],
["kla","Jon Mirande, Narrazioak","Narrazioak","Jon Mirande","narratiba",1951],
["kla","Jautarkol, Ipuiak","Ipuiak","Jautarkol","narratiba",1953],
["kla","Augustin Anabitarte, Poli","Poli","Augustin Anabitarte","narratiba",1958],
["kla","Eusebio Erkiaga, Arranegi","Arranegi","Eusebio Erkiaga","narratiba",1958],
["kla","Joxe Manuel Estonba, Izartxo","Izartxo","Joxe Manuel Estonba","narratiba",1959],
["kla","Julene Azpeitia, Amandriaren altzoan","Amandriaren altzoan","Julene Azpeitia","narratiba",1961],
["kla","Martin Ugalde, Hiltzaileak","Hiltzaileak","Martin Ugalde","narratiba",1961],
["kla","Jean Etxepare Landerretxe, Mendekoste gereziak","Mendekoste gereziak","Jean Etxepare Landerretxe","narratiba",1962],
["kla","Eusebio Erkiaga, Araibar zalduna","Araibar zalduna","Eusebio Erkiaga","narratiba",1962],
["kla","Eusebio Erkiaga, Batetik bestera","Batetik bestera","Eusebio Erkiaga","narratiba",1962],
["kla","Mariano Izeta, Dirua galgarri","Dirua galgarri","Mariano Izeta","narratiba",1962],
["kla","Jon Mirande, Haur besoetakoa","Haur besoetakoa","Jon Mirande","narratiba",1970],
["kla","Saletxe, On egiñaren obaria","On egiñaren obaria","Saletxe","narratiba",1972],
["kla","Jose Mari Satrustegi, Ekaitza","Ekaitza","Jose Mari Satrustegi","narratiba",1973],
["kla","Mikel Zarate, Haurgintza minetan","Haurgintza minetan","Mikel Zarate","narratiba",1973],
["kla","Mikel Zarate, Ipuin antzeko alegi mingotsak","Ipuin antzeko alegi mingotsak","Mikel Zarate","narratiba",1975],
["kla","Mikel Zarate, Utopiaren fantasian","Utopiaren fantasian","Mikel Zarate","narratiba",1979],
["kla","Manex Erdozaintzi-Etxart, Gauaren atzekaldean","Gauaren atzekaldean","Manex Erdozaintzi-Etxart","narratiba",1982],
["kla","Kamiñazpi, Neure lau urteko ibillerak","Neure lau urteko ibillerak","Kamiñazpi","narratiba",1989],
["kla","Zerbitzari, Ixtorio eta ipuinak","Ixtorio eta ipuinak","Zerbitzari","narratiba",0],
["itz","William Shakespeare, Hamlet","Hamlet","William Shakespeare","",1599],
["itz","Miguel Cervantes, Rinkonete eta Kortadillo","Rinkonete eta Kortadillo","Miguel Cervantes","",1613],
["itz","Madame de Lafayette, Clevesko Printzesa","Clevesko Printzesa","Madame de Lafayette","",1689],
["itz","Daniel Defoe, Robinson Crusoe","Robinson Crusoe","Daniel Defoe","",1719],
["itz","Jonathan Swift, Gulliver-en bidaiak","Gulliver-en bidaiak","Jonathan Swift","",1726],
["itz","Abbe Prevost, Manon Lescaut","Manon Lescaut","Abbe Prevost","",1731],
["itz","Lawrence Sterne, Bidaia sentimentala Frantzia eta Italian zehar","Bidaia sentimentala Frantzia eta Italian zehar","Lawrence Sterne","",1765],
["itz","Denis Diderot, Hau ez da ipuina","Hau ez da ipuina","Denis Diderot","",1772],
["itz","Pierre Choderlos de Laclos, Harreman arriskutsuak","Harreman arriskutsuak","Pierre Choderlos de Laclos","",1782],
["itz","Sade Markesa, Justine edo Bertutearen zorigaitzak","Justine edo Bertutearen zorigaitzak","Sade Markesa","",1787],
["itz","Heinrich von Kleist, Michael Kohlhaas","Michael Kohlhaas","Heinrich von Kleist","",1811],
["itz","Adelbert von Chamisso, Peter Schlemihls-en istorio miresgarria","Peter Schlemihls-en istorio miresgarria","Adelbert von Chamisso","",1814],
["itz","ETA Hoffmann, Ipuin fantastikoak","Ipuin fantastikoak","E.T.A. Hoffmann","",1814],
["itz","Prosper Merime, Mateo Falcone","Mateo Falcone","Prosper Merime","",1830],
["itz","Edgar Alan Poe, Kontakizunak","Kontakizunak","Edgar Alan Poe","",1832],
["itz","Hans Christian Andersen, Hemeretzi ipuin","Hemeretzi ipuin","Hans Christian Andersen","",1833],
["itz","Honore Balzac, Goriot Zaharra","Goriot Zaharra","Honore Balzac","",1835],
["itz","Aleksandr Pushkin, Kapitainaren alaba","Kapitainaren alaba","Aleksandr Pushkin","",1836],
["itz","George Sand, Negu bat Mallorcan","Negu bat Mallorcan","George Sand","",1839],
["itz","Alfred Musset, Zozo zuriarena","Zozo zuriarena","Alfred Musset","",1842],
["itz","Nikolai Gogol, Arima hilak","Arima hilak","Nikolai Gogol","",1842],
["itz","Charles Baudelaire, La Fanfarlo","La Fanfarlo","Charles Baudelaire","",1847],
["itz","Gerard de Nerval, Sylvie","Sylvie","Gerard de Nerval","",1854],
["itz","Gustave Flaubert, Madame Bovary","Madame Bovary","Gustave Flaubert","",1857],
["itz","Charles Baudelaire, Haxixarena","Haxixarena","Charles Baudelaire","",1858],
["itz","Charles Baudelaire, Wagner","Wagner","Charles Baudelaire","",1860],
["itz","Ivan Turgenev, Aita-semeak","Aita-semeak","Ivan Turgenev","",1862],
["itz","Pedro Antonio de Alarcon, Heriotzaren laguna","Heriotzaren laguna","Pedro Antonio de Alarcon","",1865],
["itz","Jules Verne, Michel Strogoff","Michel Strogoff","Jules Verne","",1876],
["itz","Gustave Flaubert, Bihotz sinplea","Bihotz sinplea","Gustave Flaubert","",1877],
["itz","Jan Neruda, Mala Stranako ipuinak","Mala Stranako ipuinak","Jan Neruda","",1877],
["itz","Henry James, Europarrak","Europarrak","Henry James","",1878],
["itz","Henrik Ibsen, Andere etxea","Andere etxea","Henrik Ibsen","",1879],
["itz","Guy de Maupassant, Fantasiazko ipuinak","Fantasiazko ipuinak","Guy de Maupassant","",1880],
["itz","Mark Twain, Huckleberry Finn-en abenturak","Huckleberry Finn-en abenturak","Mark Twain","",1884],
["itz","Leon Tolstoi, Ivan Ilitxen heriotza","Ivan Ilitxen heriotza","Leon Tolstoi","",1886],
["itz","Marcel Schwob, Mimoak","Mimoak","Marcel Schwob","",1893],
["itz","Bernard Shaw, Candida","Candida","Bernard Shaw","",1894],
["itz","HG Wells, Gizon ikusezina","Gizon ikusezina","H.G. Wells","",1897],
["itz","Rudyard Kipling, Kim","Kim","Rudyard Kipling","",1901],
["itz","Joseph Conrad, Ilunbeen bihotzean","Ilunbeen bihotzean","Joseph Conrad","",1902],
["itz","Ruben Dario, Fantasiazko ipuinak","Fantasiazko ipuinak","Ruben Dario","",1902],
["itz","Saki, Ipui hautatuak","Ipui hautatuak","Saki","",1902],
["itz","GK Chesterton, Ostegun izan zen gizona","Ostegun izan zen gizona","G.K. Chesterton","",1908],
["itz","Ambrose Bierce, Deabruaren hiztegia","Deabruaren hiztegia","Ambrose Bierce","",1911],
["itz","Fernando Pessoa, Marinela","Marinela","Fernando Pessoa","",1913],
["itz","Miguel Unamuno, Laino","Laino","Miguel Unamuno","",1914],
["itz","Miguel Unamuno, Abel Sanchez","Abel Sanchez","Miguel Unamuno","",1917],
["itz","Ramon Valle-Inclan, Buhame-argiak","Buhame-argiak","Ramon Valle-Inclan","",1920],
["itz","Katherine Mansfield, Lorategiko festa","Lorategiko festa","Katherine Mansfield","",1922],
["itz","John Dos Passos, Manhattan Transfer","Manhattan Transfer","John Dos Passos","",1925],
["itz","Mikhail Bulgakov, Mediku baten oroitzapenak","Mediku baten oroitzapenak","Mikhail Bulgakov","",1925],
["itz","Mikhail Bulgakov, Txakur-bihotza","Txakur-bihotza","Mikhail Bulgakov","",1925],
["itz","Virginia Woolf, Farorantz","Farorantz","Virginia Woolf","",1927],
["itz","DH Lawrence, Birjina eta ijitoa","Birjina eta ijitoa","D.H. Lawrence","",1930],
["itz","Italo Svevo, Bidaia sentimental laburra","Bidaia sentimental laburra","Italo Svevo","",1930],
["itz","John Steinbeck, Zeruko Belardiak","Zeruko Belardiak","John Steinbeck","",1932],
["itz","Evelyn Waugh, Dickens atsegin zuen gizona","Dickens atsegin zuen gizona","Evelyn Waugh","",1933],
["kla","Bernard Etxepare, Linguae Vasconum Primitiae","Linguae Vasconum Primitiae","Bernard Etxepare","poesia",1545],
["kla","Lazarraga, Euskuizkribua","Eskuizkribua","Lazarraga","poesia",1567],
["kla","Arnaud Oihenart, Oten gaztaroa neurtitzetan","O.ten gaztaroa neurtitzetan","Arnaud Oihenart","poesia",1657],
["kla","Juan Bautista Gamiz, Euskal olerkiak","Euskal olerkiak","Juan Bautista Gamiz","poesia",1748],
["kla","Jean Robin, Koplak","Koplak","Jean Robin","poesia",1758],
["kla","Kamusarri, Bertsoak","Bertsoak","Kamusarri","poesia",1834],
["kla","Agustin Paskual Iturriaga, Ipuinak","Ipuinak","Agustin Paskual Iturriaga","poesia",1842],
["kla","Jean Martin Hiribarren, Iruñeko bestak","Iruñeko bestak","Jean Martin Hiribarren","poesia",1845],
["kla","Jean Baptiste Arxu, Alhegia bereziak","La Fontainaren Aleghia berheziak neurt-hitzez","Jean Baptiste Arxu","poesia",1848],
["kla","Joanes Otxalde, Koplak","Koplak","Joanes Otxalde","poesia",1851],
["kla","Zaldubi, Kantikak era neurtitzak","Kantikak era neurtitzak","Zaldubi","poesia",1851],
["kla","Goietxe, Alegiak","Fableak edo Alegiak","Martin Goietxe","poesia",1852],
["kla","Jean Martin Hiribarren, Montebideoko berriak","Montebideoko berriak","Jean Martin Hiribarren","poesia",1853],
["kla","Jean Martin Hiribarren, Napoleon Lehena","Napoleon Lehena","Jean Martin Hiribarren","poesia",1856],
["kla","Jose Mendiage, Kantak","Kantak","Jose Mendiage","poesia",1863],
["kla","Piarres Ibarrart, Koplak","Koplak","Piarres Ibarrart","poesia",1869],
["kla","Serafin Baroja, Gazi-gezak","Gazi-gezak","Serafin Baroja","poesia",1875],
["kla","Sabino Arana Goiri, Olerkijak","Olerkijak","Sabino Arana Goiri","poesia",1894],
["kla","Pedro Mari Otaño, Zerbait","Zerbait","Pedro Mari Otaño","poesia",1895],
["kla","Frantzisko Lopez Alen, Josetxo","Josetxo","Frantzisko Lopez Alen","poesia",1896],
["kla","Eusebio Maria Azkue, Parnasorako bidea","Parnasorako bidea","Eusebio Maria Azkue","poesia",1896],
["kla","Juan Kruz Zapirain, Brabanteko Jenobeba","Brabanteko Jenobeba","Juan Kruz Zapirain","poesia",1899],
["kla","Felipe Arrese Beitia, Ama euskeriaren liburu kantaria","Ama euskeriaren liburu kantaria","Felipe Arrese Beitia","poesia",1900],
["kla","Felipe Arrese Beitia, Asti orduetako bertsozko lanak","Asti orduetako bertsozko lanak","Felipe Arrese Beitia","poesia",1902],
["kla","Pedro Mari Otaño, Alkar","Alkar","Pedro Mari Otaño","poesia",1904],
["kla","Emeterio Arrese, Nere bidean","Nere bidean","Emeterio Arrese","poesia",1913],
["kla","Bingen Aizkibel, Urretxinddorra","Urretxinddorra","Bingen Aizkibel","poesia",1918],
["kla","Iratzeder, Pindar eta lano","Pindar eta lano","Iratzeder","poesia",1920],
["kla","Oxobi, Lan orhoitgarri zonbait","Lan orhoitgarri zonbait","Oxobi","poesia",1926],
["kla","Paulo Zamarripa, Gora begira","Gora begira","Paulo Zamarripa","poesia",1927],
["kla","Emeterio Arrese, Txindor","Txindor","Emeterio Arrese","poesia",1928],
["kla","Jautarkol, Biozkadak","Biozkadak","Jautarkol","poesia",1929],
["kla","Loramendi, Olerkiak","Olerkiak","Loramendi","poesia",1930],
["kla","Lauaxeta, Bide barrijak","Bide barrijak","Lauaxeta","poesia",1931],
["kla","Xabier Lizardi, Biotz-begietan","Biotz-begietan","Xabier Lizardi","poesia",1932],
["kla","Joseba Zubimendi, Aberri oyuak","Aberri oyuak","Joseba Zubimendi","poesia",1932],
["kla","Orixe, Barne muinetan","Barne muinetan","Orixe","poesia",1934],
["kla","Xabier Lizardi, Umezurtz olerkiak","Umezurtz olerkiak","Xabier Lizardi","poesia",1934],
["kla","Lauaxeta, Arrats Beran","Arrats Beran","Lauaxeta","poesia",1935],
["kla","Joseba Zubimendi, Zumalakarregi","Zumalakarregi","Joseba Zubimendi","poesia",1935],
["kla","Lotsati, Poemak","Poemak","Lotsati","poesia",1935],
["kla","Telesforo Monzon, Urrundik","Urrundik","Telesforo Monzon","poesia",1945],
["kla","Telesforo Monzon, Gudarien egiñak","Gudarien egiñak","Telesforo Monzon","poesia",1947],
["kla","Federiko Krutwig, Poemak","Poemak","Federiko Krutwig","poesia",1949],
["kla","Jon Mirande, Poemak","Poemak","Jon Mirande","poesia",1950],
["kla","Orixe, Olerkiak","Olerkiak","Orixe","poesia",1950],
["kla","Salbatore Mitxelena, Arraun ta amets","Arraun ta amets","Salbatore Mitxelena","poesia",1955],
["kla","Nemesio Etxaniz, Lur berri billa","Lur berri billa","Nemesio Etxaniz","poesia",1967],
["kla","Beñat Mardo, Koplak","Koplak","Beñat Mardo","poesia",0],
["kla","Bordel, Bordel bertsularia","Bordel bertsularia","Bordel","poesia",0],
["kla","Salbat Monho, Olerkiak","Olerkiak","Salbat Monho","poesia",0],
["kla","Juan Mateo Zabala, Alegiak","Alegiak","Juan Mateo Zabala","poesia",0],
["kla","Etxahun, Bertsoak eta kantak","Bertsoak eta kantak","Etxahun","poesia",0],
["kla","Xabier Munibe, Gabon sariak","Gabon sariak","Xabier Munibe","antzerkia",1762],
["kla","Xabier Munibe, El borracho burlado","El borracho burlado","Peñafloridako Kondea","antzerkia",1764],
["kla","Jakes Oihenarte, Kaniko eta Belxitina","Kaniko eta Belxitina","Jakes Oihenarte","antzerkia",1848],
["kla","Marzelino Soroa, Anton Kaiku","Anton Kaiku","Marzelino Soroa","antzerkia",1882],
["kla","Piarres Harispe, Karmela","Karmela","Piarres Harispe","antzerkia",1886],
["kla","Toribio Altzaga, Aterako gera","Aterako Gera!","Toribio Altzaga","antzerkia",1888],
["kla","Resurreccion M Azkue, Vizcaytik Bizkaira","Vizcaytik Bizkaira","Resurreccion Maria Azkue","antzerkia",1895],
["kla","Juan Ignazio Uranga, Aritzaren zumo gozua","Aritzaren zumo gozua","Juan Ignazio Uranga","antzerkia",1896],
["kla","Pedro Ignazio Barrutia, Gabonetarako ikuskizuna","Gabonetarako ikuskizuna","Pedro Ignazio Barrutia","antzerkia",1897],
["kla","Pepe Artola, Lehorreko arrantzalea","Lehorreko arrantzalea","Pepe Artola","antzerkia",1898],
["kla","Pedro Mari Otaño, Artzai mutilla","Artzai mutilla","Pedro Mari Otaño","antzerkia",1900],
["kla","Juan Ignazio Uranga, Manu","Manu","Juan Ignazio Uranga","antzerkia",1901],
["kla","Pedro Mari Otaño, Lora","Lora","Pedro Mari Otaño","antzerkia",1907],
["kla","Juan Ignazio Uranga, Bakarrizketak","Bakarrizketak","Juan Ignazio Uranga","antzerkia",1908],
["kla","Resurreccion M Azkue, Ortzuri","Ortzuri","Resurreccion Maria Azkue","antzerkia",1909],
["kla","Juan Ignazio Uranga, Neska jakinzaleai","Neska jakinzaleai iru bakarizketa","Juan Ignazio Uranga","antzerkia",1909],
["kla","Etienne Decrept, Maitena","Maitena","Etienne Decrept","antzerkia",1910],
["kla","Resurreccion M Azkue, Urlo","Urlo","Resurreccion Maria Azkue","antzerkia",1911],
["kla","Alfonso Maria Zabala, Periyaren zalapartak","Periyaren zalapartak","Alfonso Maria Zabala","antzerkia",1911],
["kla","Jose Elizondo, Alkate ona","Alkate ona","Jose Elizondo","antzerkia",1912],
["kla","Ignazio Nuñez Arizmendi, Porru salda","Porru salda","Ignazio K. Nuñez Arizmendi","antzerkia",1912],
["kla","Alfonso Maria Zabala, Jauregi errotako astoa","Jauregi errotako astoa","Alfonso Maria Zabala","antzerkia",1912],
["kla","Emeterio Arrese, Zara","Zara","Emeterio Arrese","antzerkia",1913],
["kla","Jose Eizagirre, Basotarrak","Basotarrak","Jose Eizagirre","antzerkia",1913],
["kla","Pepe Artola, Motxa erriyan","Motxa erriyan","Pepe Artola","antzerkia",1913],
["kla","Etienne Decrept, Amatxi","Amatxi","Etienne Decrept","antzerkia",1914],
["kla","Kaietano Sanchez Irure, Azken beltza","Azken beltza","Kaietano Sanchez Irure","antzerkia",1915],
["kla","Ignazio Nuñez Arizmendi, Ebaisto","Ebaisto","Ignazio K. Nuñez Arizmendi","antzerkia",1915],
["kla","Katalina Eleizegi, Garbiñe","Garbiñe","Katalina Eleizegi","antzerkia",1916],
["kla","Etienne Decrept, Semetxia","Semetxia","Etienne Decrept","antzerkia",1917],
["kla","Alfonso Maria Zabala, Melitonaren bi senarrak","Melitonaren bi senarrak","Alfonso Maria Zabala","antzerkia",1918],
["kla","Alfonso Maria Zabala, Urruti-izketa","Urruti-izketa","Alfonso Maria Zabala","antzerkia",1918],
["kla","Juan Iruretagoiena, Gau-ostatua","Gau-ostatua, eta beste","Juan Iruretagoiena","antzerkia",1921],
["kla","Ander Arzelus, Gibel handi","Gibel handi","Luzear","antzerkia",1929],
["kla","Lauaxeta, Asarre-aldija","Asarre-aldija","Lauaxeta","antzerkia",1931],
["kla","Antonio Maria Labaien, Euskal-eguna","Euskal-eguna","Antonio Maria Labaien","antzerkia",1931],
["kla","Lauaxeta, Balbia","Balbia","Lauaxeta","antzerkia",1932],
["kla","Lauaxeta, Epaya","Epaya","Lauaxeta","antzerkia",1932],
["kla","Xabier Lizardi, Bi ahizpak","Bi ahizpak","Xabier Lizardi","antzerkia",1932],
["kla","Xabier Lizardi, Laino eta Izar","Laino eta Izar","Xabier Lizardi","antzerkia",1932],
["kla","Antonio Maria Labaien, Mateo Txistu","Mateo Txistu","Antonio Maria Labaien","antzerkia",1932],
["kla","Lauaxeta, Iru gudari","Iru gudari","Lauaxeta","antzerkia",1933],
["kla","Antonio Maria Labaien, Iparragirre","Iparragirre","Antonio Maria Labaien","antzerkia",1933],
["kla","Antonio Maria Labaien, Galtzaundi","Galtzaundi","Antonio Maria Labaien","antzerkia",1935],
["kla","Antonio Maria Labaien, Iruñxeme","Iruñxeme","Antonio Maria Labaien","antzerkia",1935],
["kla","Manuel Lekuona, Eun dukat","Eun dukat","Manuel Lekuona","antzerkia",1935],
["kla","Piarres Larzabal, Nork hil du Oihanalde","Nork hil du Oihanalde","Piarres Larzabal","antzerkia",1950],
["kla","Piarres Larzabal, Xirristi-mirrixti","Xirristi-mirrixti","Piarres Larzabal","antzerkia",1950],
["kla","Paul Gilsou, Petan Mihiku","Petan Mihiku","Paul Gilsou","antzerkia",1951],
["kla","Xabier Lizardi, Ezkondu ezin ziteken mutila","Ezkondu ezin ziteken mutila","Xabier Lizardi","antzerkia",1953],
["kla","Piarres Larzabal, Hila espos","Hila espos","Piarres Larzabal","antzerkia",1955],
["kla","Piarres Larzabal, Herriko botzak","Herriko botzak","Piarres Larzabal","antzerkia",1956],
["kla","Telesforo Monzon, Lau kantari eta xori bat","Lau kantari eta xori bat","Telesforo Monzon","antzerkia",1956],
["kla","Piarres Larzabal, Hiru ziren","Hiru ziren","Piarres Larzabal","antzerkia",1957],
["kla","Telesforo Monzon, Menditarrak","Menditarrak","Telesforo Monzon","antzerkia",1957],
["kla","Nemesio Etxaniz, Gabak zekarren eguna","Gabak zekarren eguna","Nemesio Etxaniz","antzerkia",1958],
["kla","Nemesio Etxaniz, Gabon-zauria","Gabon-zauria","Nemesio Etxaniz","antzerkia",1958],
["kla","Nemesio Etxaniz, Maite ere... neurriz","Maite ere... neurriz","Nemesio Etxaniz","antzerkia",1958],
["kla","Nemesio Etxaniz, Zotzean bizia","Zotzean bizia","Nemesio Etxaniz","antzerkia",1958],
["kla","Piarres Larzabal, Mugari tiro","Mugari tiro","Piarres Larzabal","antzerkia",1959],
["kla","Antonio Maria Labaien, Jokua ez da errenta","Jokua ez da errenta","Antonio Maria Labaien","antzerkia",1960],
["kla","Telesforo Monzon, Gure behia hil da","Gure behia hil da","Telesforo Monzon","antzerkia",1960],
["kla","Piarres Larzabal, Senperen gertatua","Senperen gertatua","Piarres Larzabal","antzerkia",1964],
["kla","Piarres Larzabal, Lana eri","Lana eri","Piarres Larzabal","antzerkia",1965],
["kla","Telesforo Monzon, Eneko Bizkai eta Maria Lorka","Eneko Bizkai eta Maria Lorka","Telesforo Monzon","antzerkia",1966],
["kla","Telesforo Monzon, Hazparneko Anderea","Hazparneko Anderea","Telesforo Monzon","antzerkia",1966],
["kla","Antonio Maria Labaien, Kalifornia ku-ku","Kalifornia ku-ku","Antonio Maria Labaien","antzerkia",1967],
["kla","Piarres Larzabal, Nor da hobenduna","Nor da hobenduna","Piarres Larzabal","antzerkia",1968],
["kla","Antonio Maria Labaien, Agarren seme... Ismael","Agarren seme... Ismael","Antonio Maria Labaien","antzerkia",1970],
["kla","Piarres Larzabal, Angles ginelarik","Angles ginelarik","Piarres Larzabal","antzerkia",1973],
["kla","Zerbitzari, Bi gogorrak","Bi gogorrak","Zerbitzari","antzerkia",0],
["kla","Mongongo Dasanza, Laborarien abisua","Laborarien abisua","Mongongo Dasanza","saiakera",1692],
["kla","Etxeberri Sarakoa, Lau-Urduri gomendiozko karta","Lau-Urduri gomendiozko karta, edo guthuna","Etxeberri Sarakoa","saiakera",1718],
["kla","Agustin Kardaberaz, Euskeraren berri onak","Euskeraren berri onak","Agustin Kardaberaz","saiakera",1761],
["kla","Jusef Egiategi, Filosofo huscaldunaren ekheia","Filosofo Huskaldunaren ekheia","Jusef Egiategi","saiakera",1785],
["kla","Juan Ignazio Iztueta, Gipuzkoako dantza gogoangarrien kondaira","Gipuzkoako dantza gogoangarrien kondaira","Juan Ignazio Iztueta","saiakera",1824],
["kla","Bertrand Goienetxe, Marechalen liburia","Marechalen liburia","Bertrand Goienetxe","saiakera",1830],
["kla","Agosti Xaho, Azti-begia","Azti-begia eta beste izkribu zenbait","Agosti Xaho","saiakera",1834],
["kla","Agustin Iturriaga, Euskal dialogoak","Euskal dialogoak","Agustin Paskual Iturriaga","saiakera",1842],
["kla","Juan Ignazio Iztueta, Gipuzkoako probintziaren kondaira","Gipuzkoako probintziaren kondaira","Juan Ignazio Iztueta","saiakera",1847],
["kla","Jean Pierre Duvoisin, Laborantzako liburua","Laborantzako liburua","Jean Pierre Duvoisin","saiakera",1858],
["kla","Jean Pierre Duvoisin, Baigorriko zazpi liliak","Baigorriko zazpi liliak","Jean Pierre Duvoisin","saiakera",1884],
["kla","Arnaud Abbadie, Laborarier","Laborarier","Arnaud Abbadie","saiakera",1887],
["kla","Mixel Elizanburu, Lehenagoko Eskualdunak zer ziren","Lehenagoko Eskualdunak zer ziren","Mixel Elizanburu","saiakera",1889],
["kla","Arnaud Abbadie, Aphezak soldado","Aphezak soldado","Arnaud Abbadie","saiakera",1890],
["kla","Laurent Diharasarri, Aphezen dretxoak eta eginbideak eletzionetan","Aphezen dretxoak eta eginbideak eletzionetan","Laurent Diharasarri","saiakera",1890],
["kla","Mixel Elizanburu, Frantziako hirur Errepubliken","Frantziako hirur errepubliken ixtorioa laburzki","Mixel Elizanburu","saiakera",1890],
["kla","Jean Hiriart Urruti, Gontzetarik","Gontzetarik jalgiaraziak","Jean Hiriart Urruti","saiakera",1891],
["kla","Martin Aranburu, Osasun legeak","Osasun legeak","Martin Aranburu","saiakera",1899],
["kla","Jean Baptiste Althabe, Ziberuko botanika edo lantharen jakitatia","Ziberuko botanika edo lantharen jakitatia","Jean Baptiste Althabe","saiakera",1900],
["kla","Martin Aranburu, Erari espirituzkoak","Erari espirituzkoak","Martin Aranburu","saiakera",1901],
["kla","Jean Baptiste Althabe, Hunkailu berrien enthelegia Ziberuko laborarier","Hunkailu berrien enthelegia Ziberuko laborarier","Jean Baptiste Althabe","saiakera",1904],
["kla","Jean Etxepare, Buruxkak","Buruxkak","Jean Etxepare","saiakera",1910],
["kla","Kirikiño, Edo geuk edo iñok ez","Edo geuk edo iñok ez","Kirikiño","saiakera",1913],
["kla","Larreko, Nafarroatik","Nafarroatik","Larreko","saiakera",1916],
["kla","Larreko, Lekukotasuna","Lekukotasuna","Larreko","saiakera",1916],
["kla","Federiko Garralda, Aurrendako dostatzia","Aurrendako dostatzia","Federiko Garralda","saiakera",1926],
["kla","Orixe, Atze edo edesti laburra","Atze edo edesti laburra","Orixe","saiakera",1927],
["kla","Zerbitzari, Azkaine gure sorterria","Azkaine gure sorterria","Zerbitzari","saiakera",1928],
["kla","Manezaundi, Artikulu bilduma","Artikulu bilduma","Manezaundi","saiakera",1928],
["kla","Gurbindo, Kazetari lanak","Kazetari lanak","Gurbindo","saiakera",1930],
["kla","Lauaxeta, Azalpenak","Azalpenak","Lauaxeta","saiakera",1931],
["kla","Lauaxeta, Azalpenak eta beste","Azalpenak eta beste 1932","Lauaxeta","saiakera",1932],
["kla","Xabier Lizardi, Itz-lauz","Itz-lauz","Xabier Lizardi","saiakera",1934],
["kla","Juan Bautista Eguzkitza, Gizarte auzia","Gizarte auzia","Juan Bautista Eguzkitza","saiakera",1935],
["kla","Telesforo Monzon, Langosta baten inguruan","Langosta baten inguruan","Telesforo Monzon","saiakera",1949],
["kla","Orixe, Kiton arrebarekin","Kiton arrebarekin","Orixe","saiakera",1950],
["kla","Jon Mirande, Artikuluak","Artikuluak","Jon Mirande","saiakera",1951],
["kla","Salbatore Mitxelena, Unamuno ta Abendats","Unamuno ta Abendats","Salbatore Mitxelena","saiakera",1958],
["kla","Jean Pierre Xabalgoiti, Laborarien abisua","Laborarien abisua","Jean Pierre Xabalgoiti","saiakera",0],
["kla","Etxeberri Sarakoa, Eskual-Herriko gazteriari","Eskual-Herriko gazteriari","Etxeberri Sarakoa","saiakera",0],
["kla","Etxeberri Sarakoa, Eskuararen hatsapenak","Eskuararen hatsapenak","Etxeberri Sarakoa","saiakera",0],
["kla","Batxi, Hau mundu arrano hau","Hau mundu arrano hau","Batxi","kronika",1914],
["kla","Zerbitzari, 57a gerlan","57a gerlan","Zerbitzari","kronika",1914],
["kla","Jean Etxepare, Beribilez","Beribilez","Jean Etxepare","kronika",1931],
["kla","Augustin Anabitarte, Aprikako basamortuan","Aprikako basamortuan","Augustin Anabitarte","kronika",1961],
["kla","Zerbitzari, Metsikorat","Metsikorat","Zerbitzari","kronika",0],
["kla","Joanes Leizarraga, Testamentu Berria","Iesus Krist Gure Iaunaren Testamentu Berria","Joanes Leizarraga","erlijioa",1571],
["kla","Betolatza, Doctrina Christiana","Doktrina Kristiana","Betolaza","erlijioa",1596],
["kla","Estebe Materre, Dotrina kristiana","Dotrina kristiana","Estebe Materre","erlijioa",1617],
["kla","Juan Beriain, Nola enzun bear den meza","Tratazen da nola enzun bear den meza","Juan Beriain","erlijioa",1621],
["kla","Juan Beriain, Dotrina kristioarena","Dotrina kristioarena euskaras","Juan Beriain","erlijioa",1626],
["kla","Etxeberri Ziburukoa, Manual debozionezkoa","Manual debozionezkoa","Etxeberri Ziburukoa","erlijioa",1627],
["kla","Joanes Haranburu, Debozino eskuarra","Debozino eskuarra","Joanes Haranburu","erlijioa",1635],
["kla","Axular, Gero","Gero","Axular","erlijioa",1643],
["kla","Martin Otxoa Kapanaga, Dotrinea","Dotrinea","Martin Otxoa Kapanaga","erlijioa",1656],
["kla","Kristobal Harizmendi, Ama birjinaren ofizioa","Ama birjinaren ofizioa","Kristobal Harizmendi","erlijioa",1658],
["kla","Silvain Pouvreau, Filotea","Filotea","Silvain Pouvreau","erlijioa",1664],
["kla","Pierre Argaiñaratz, Deboten brebiarioa","Deboten brebiarioa","Pierre Argaiñaratz","erlijioa",1665],
["kla","Juan Tartas, Onsa hilzeko bidia","Onsa hilzeko bidia","Juan Tartas","erlijioa",1666],
["kla","Silvain Pouvreau, Iesusen imitazionea","Iesusen imitazionea","Silvain Pouvreau","erlijioa",1669],
["kla","Juan Tartas, Arima penitentearen okupatione debotak","Arima penitentearen okupazione debotak","Juan Tartas","erlijioa",1672],
["kla","Aranbillaga, Jesu Kristoren Imitazionea","Jesu Kristoren Imitazionea","Aranbillaga","erlijioa",1684],
["kla","Bernard Gazteluzar, Egia katholikak","Egia katholikak","Bernard Gazteluzar","erlijioa",1686],
["kla","Athanase Belapeire, Katexima laburra","Katexima labürra","Athanase Belapeire","erlijioa",1696],
["kla","Pierre Urte, Ethorkia eta Ilkhitzea","Ethorkia eta Ilkhitzea","Pierre Urte","erlijioa",1700],
["kla","Jose Otxoa de Arin, Explikazioa","Doktrina kristianaren explikazioa","Jose Otxoa Arin","erlijioa",1713],
["kla","Mixel Xurio, Jesu-Kristoren imitazionea","Jesu-Kristoren imitazionea","Mixel Xurio","erlijioa",1720],
["kla","Manuel Larramendi, Euskal testuak","Euskal testuak","Manuel Larramendi","erlijioa",1729],
["kla","Martin Arzadun, Doktrina kristianeen explikazinoa","Doktrina kristianeen explikazinoa","Martin Arzadun","erlijioa",1731],
["kla","Juan Irazusta, Doktrina kristiana","Doktrina kristiana","Juan Irazusta","erlijioa",1739],
["kla","Joanes Haraneder, Gudu izpirituala","Gudu izpirituala","Joanes Haraneder","erlijioa",1750],
["kla","Joseph Mikelestorena, Zerura nai duenak","Zerura nai duenak ar dezaken bide erraza","Joseph Mikelestorena","erlijioa",1751],
["kla","Martin Maister, Jesu-Kristen imitazionia","Jesü-Kristen imitazionia","Martin Maister","erlijioa",1757],
["kla","Sebastian Mendiburu, Zenbait otoitz-gai-I","Jesusen amore-nekeei dagozten zenbait otoitzgai (I)","Sebastian Mendiburu","erlijioa",1759],
["kla","Sebastian Mendiburu, Zenbait otoitz-gai-II","Zenbait otoitz-gai-II","Sebastian Mendiburu","erlijioa",1760],
["kla","Sebastian Mendiburu, Zenbait otoitz-gai-III","Zenbait otoitz-gai-III","Sebastian Mendiburu","erlijioa",1760],
["kla","Bartolome Olaetxea, Dotrina Cristianea","Dotrina Cristianea","Bartolome Olaetxea","erlijioa",1763],
["kla","Agustin Kardaberaz, Justuen ispillu argia","Justuen Ispillu argia","Agustin Kardaberaz","erlijioa",1764],
["kla","Bernard Larregi, Testamen zaharreko historioa","Testamen zaharreko historioa","Bernard Larregi","erlijioa",1775],
["kla","Bernard Larregi, Testamen berriko historioa","Testamen berriko historioa","Bernard Larregi","erlijioa",1777],
["kla","Bernard Larregi, Zenbeit sainduen bizitzea","Zenbeit sainduen bizitzea","Bernard Larregi","erlijioa",1777],
["kla","Alexander Mihura, Andredena Mariaren imitazionea","Andredena Mariaren imitazionea","Alexander Mihura","erlijioa",1778],
["kla","Andre Baraziart, Meditazione ttipiak","Giristinoki bizitzeko eta hiltzeko moldea","Andre Baraziart","erlijioa",1784],
["kla","Juan Antonio Ubillos, Kristau berri-ekarlea","Kristau berri-ekarlea","Juan Antonio Ubillos","erlijioa",1785],
["kla","Joakin Lizarraga, Zenbait sanduen biziak asteaz datozinak","Zenbait sanduen biziak asteaz datozinak","Joakin Lizarraga","erlijioa",1793],
["kla","Juan Antonio Mogel, Konfesio ta komunioko","Konfesio ta komunioko sakramentuen gañean erakasteak","Juan Antonio Mogel","erlijioa",1800],
["kla","Juan Bautista Agirre, Konfesioko eta komunioko sakramentuen ganean erakusaldiak","Konfesioko eta komunioko sakramentuen gañean erakusaldiak","Juan Bautista Agirre","erlijioa",1803],
["kla","Pedro Antonio Añibarro, Lora sorta espirituala","Lora sorta espirituala","Pedro Antonio Añibarro","erlijioa",1803],
["kla","Jose Ignazio Gerriko, Kristau dotrina-I","Kristau dotrina-I","Jose Ignazio Gerriko","erlijioa",1805],
["kla","Jose Ignazio Gerriko, Kristau dotrina-II","Kristau dotrina-II","Jose Ignazio Gerriko","erlijioa",1805],
["kla","Juan Bautista Agirre, Erakusaldiak-I","Erakusaldiak-I","Juan Bautista Agirre","erlijioa",1808],
["kla","Martin Duhalde, Meditazioneak","Meditazioneak gei premiatsuenen gainean","Martin Duhalde","erlijioa",1809],
["kla","Juan Bautista Agirre, Erakusaldiak-II","Erakusaldiak-II","Juan Bautista Agirre","erlijioa",1814],
["kla","Frai Bartolome, Olgeeta ta dantzeen","Euskal Errijetako olgeeta ta dantzeen neurrizko gatz-ozpinduba","Frai Bartolome","erlijioa",1816],
["kla","Juan Bautista Agirre, Erakusaldiak-III","Erakusaldiak-III","Juan Bautista Agirre","erlijioa",1817],
["kla","Pedro Astarloa, Urteko domeka gustijetarako berbaldiak","Urteko domeka gustijetarako berbaldi ikasbidekuak (II)","Pedro Astarloa","erlijioa",1818],
["kla","Juan Jose Mogel, Egunoroko lan-on ta erregubak","Egunoroko lan-on ta erregubak","Juan Jose Mogel","erlijioa",1820],
["kla","Jose Antonio Uriarte, Marijaren illa","Marijaren illa","Jose Antonio Uriarte","erlijioa",1850],
["kla","Francisco Ignacio Lardizabal, Testamentu Berriko Kondaira","Testamentu Berriko Kondaira","Francisco Ignacio Lardizabal","erlijioa",1855],
["kla","Francisco Ignacio Lardizabal, Testamentu zarreko kondaira","Testamentu zarreko kondaira","Francisco Ignacio Lardizabal","erlijioa",1855],
["kla","Pedro Prudencio Hualde Maio, Gore Jeinaren Ebanjelio Saintiua","Gore Jeinaren Ebanjelio Saintiua","Pedro Prudencio Hualde Maio","erlijioa",1855],
["kla","Jean Martin Hiribarren, Eskaraz egia","Eskaraz egia","Jean Martin Hiribarren","erlijioa",1858],
["kla","Franzisko Laphitz, Bi Saindu Hescualdunen Bizia","Bi Saindu Heskualdunen Bizia","Franzisko Laphitz","erlijioa",1867],
["kla","Jose Inazio Arana, San Ignazio Loiolakoaren bizitza laburtua","San Ignazio Loiolakoaren bizitza laburtua","Jose Inazio Arana","erlijioa",1872],
["kla","Krispin Beobide, Asisko loria","Asisko loria","Krispin Beobide","erlijioa",1885],
["kla","Bazilio Johanategi, San Benoat","San Benoaten bizitzea","Bazilio Joanategi","erlijioa",1887],
["kla","Jean Pierre Arbelbide, Bokazionea","Bokazionea","Jean Pierre Arbelbide","erlijioa",1887],
["kla","Jose Ignazio Arana, Bai pekatu da liberalkeriya","Bai, pekatu da liberalkeriya","Jose Ignazio Arana","erlijioa",1888],
["kla","Bazilio Joanategi, Sainduen bizitzea","Sainduen bizitzea","Bazilio Joanategi","erlijioa",1890],
["kla","Jean Pierre Arbelbide, Erlisionea","Erlisionea","Jean Pierre Arbelbide","erlijioa",1890],
["kla","Etienne Lapeyre, Credo edo Sinhesten dut esplikatua","Credo edo Sinhesten dut esplikatua","Etiene Lapeire","erlijioa",1891],
["kla","Emanuel Intxauspe, Maria birjinaren hilabetia","Maria birjinaren hilabetia","Emanuel Intxauspe","erlijioa",1894],
["kla","Jean Pierre Arbelbide, Igandea edo Jaunaren eguna","Igandea edo Jaunaren eguna","Jean Pierre Arbelbide","erlijioa",1895],
["kla","Manuel Antonio Antia, San Frantzisko Asiskoaren bizitza","San Frantzisko Asiskoaren bizitza","Manuel Antonio Antia","erlijioa",1901],
["kla","Franzisko Goñi, Ama Birjiñaren agertziak","Ama Birjiñaren agertziak","Franzisko Goñi","erlijioa",1906],
["kla","Leon Leon, Jesu-Kristoren imitazionea","Jesu-Kristoren imitazionea","Leon Leon","erlijioa",1929]];
