/* Libros para niños y lectores principiantes, por idioma de lectura. Se mezclan en el catálogo de cada
   idioma con un distintivo de nivel y tienen su propio filtro ("Infantil y principiantes").
   Fuentes: `gb` = ID de Project Gutenberg (EPUB vía el proxy; `noimages` pide la versión sin
   imágenes cuando la ilustrada pesa decenas de MB); `ws` = título exacto de una página de
   Wikisource en ese idioma (API con CORS, sin proxy). GENERADO por tools/build_beginners.py a partir
   del bloque JSON de docs/libros-infantiles-<idioma>.md; no editar a mano. */
window.BEGINNERS = {
  es: [
    { gb: 36558, title: "Ratón Pérez", author: "Luis Coloma", level: "infantil" },
    { gb: 55206, noimages: true, title: "Fábulas de Samaniego", author: "Félix María de Samaniego", level: "infantil" },
    { gb: 29497, title: "Fábulas literarias", author: "Tomás de Iriarte", level: "infantil" },
    { gb: 64058, title: "Fábulas y cuentos en verso", author: "Varios", level: "infantil" },
    { ws: "es", title: "Cuentos de hadas (Baró tr.)", author: "Charles Perrault", level: "infantil" },
    { ws: "es", title: "Cuentos de hadas (Coll i Vehí tr.)", author: "Perrault y d'Aulnoy", level: "infantil" },
    { ws: "es", title: "Cuentos escogidos de los Hermanos Grimm", author: "Hermanos Grimm", level: "infantil" },
    { ws: "es", title: "Hansel y Gretel", author: "Hermanos Grimm", level: "infantil" },
    { ws: "es", title: "Cuentos de Andersen", author: "Hans Christian Andersen", level: "infantil" },
    { ws: "es", title: "Cuentos clásicos para niños", author: "Hans Christian Andersen", level: "infantil" },
    { ws: "es", title: "El almacén de los niños", author: "Jeanne-Marie Leprince de Beaumont", level: "infantil" },
    { ws: "es", title: "Cuentos, adivinanzas y refranes populares", author: "Fernán Caballero", level: "infantil" },
    { ws: "es", title: "Cuentos para gente menuda", author: "Romualdo Nogués", level: "infantil" },
    { ws: "es", title: "Brisas de primavera", author: "Julia de Asensi", level: "infantil" },
    { gb: 19898, title: "La Edad de Oro", author: "José Martí", level: "infantil" },
    { ws: "es", title: "Cuentos de la selva", author: "Horacio Quiroga", level: "infantil" },
    { gb: 69164, title: "Cuentos chilenos de nunca acabar", author: "Ramón A. Laval", level: "infantil" },
    { gb: 55215, noimages: true, title: "Cuando la tierra era niña", author: "Nathaniel Hawthorne", level: "infantil" },
    { ws: "es", title: "El renacuajo paseador", author: "Rafael Pombo", level: "infantil" },
    { ws: "es", title: "Cutufato y su gato", author: "Rafael Pombo", level: "infantil" },
    { ws: "es", title: "Canciones infantiles (1880)", author: "Tradicional", level: "infantil" },
    { gb: 11047, noimages: true, title: "Libro segundo de lectura", author: "Ellen M. Cyr", level: "principiante" },
    { ws: "es", title: "Libro primero de lectura", author: "Ellen M. Cyr", level: "principiante" },
    { ws: "es", title: "Lecturas infantiles", author: "José Ortega Munilla", level: "principiante" },
    { gb: 24250, noimages: true, title: "Lecturas fáciles con ejercicios", author: "Varios", level: "principiante" },
    { gb: 36805, title: "Spanish Tales for Beginners", author: "Elijah Clarence Hills (ed.)", level: "principiante" },
    { gb: 15353, title: "A First Spanish Reader", author: "Erwin W. Roessler y Alfred Remy", level: "principiante" },
    { gb: 22065, title: "An Elementary Spanish Reader", author: "Earl Stanley Harrison", level: "principiante" },
    { gb: 12435, title: "Páginas sudamericanas", author: "Varios", level: "principiante" },
    { gb: 63464, title: "Nuestra Pampa, libro de lectura", author: "Varios", level: "principiante" },
    { ws: "es", title: "El príncipe feliz", author: "Oscar Wilde", level: "principiante" },
    { ws: "es", title: "El gigante egoísta", author: "Oscar Wilde", level: "principiante" },
    { ws: "es", title: "El ruiseñor y la rosa", author: "Oscar Wilde", level: "principiante" },
    { gb: 73486, noimages: true, title: "Corazón", author: "Edmondo de Amicis", level: "intermedio" },
    { gb: 69552, noimages: true, title: "El libro de las tierras vírgenes", author: "Rudyard Kipling", level: "intermedio" },
    { gb: 45438, title: "La isla del tesoro", author: "Robert Louis Stevenson", level: "intermedio" },
    { gb: 62201, title: "Los ladrones de Londres (Oliver Twist)", author: "Charles Dickens", level: "intermedio" },
    { ws: "es", title: "Las aventuras de Tom Sawyer (edición)", author: "Mark Twain", level: "intermedio" },
    { ws: "es", title: "Viaje al centro de la Tierra", author: "Julio Verne", level: "intermedio" },
    { gb: 63424, title: "Cuentos populares en Chile", author: "Ramón A. Laval", level: "intermedio" },
    { gb: 52262, title: "Cuentos de la Alhambra", author: "Washington Irving", level: "intermedio" },
    { gb: 47287, title: "El libro de las mil noches y una noche, tomo 1", author: "Anónimo", level: "intermedio" },
  ],
  en: [
    { gb: 14838, title: "The Tale of Peter Rabbit", author: "Beatrix Potter", level: "infantil" },
    { gb: 14848, title: "The Story of Miss Moppet", author: "Beatrix Potter", level: "infantil" },
    { gb: 14837, title: "The Tale of Tom Kitten", author: "Beatrix Potter", level: "infantil" },
    { gb: 14407, noimages: true, title: "The Tale of Benjamin Bunny", author: "Beatrix Potter", level: "infantil" },
    { gb: 14814, noimages: true, title: "The Tale of Jemima Puddle-Duck", author: "Beatrix Potter", level: "infantil" },
    { gb: 14872, noimages: true, title: "The Tale of Squirrel Nutkin", author: "Beatrix Potter", level: "infantil" },
    { gb: 45264, title: "The Tale of Two Bad Mice", author: "Beatrix Potter", level: "infantil" },
    { gb: 10469, title: "Johnny Crow's Garden", author: "L. Leslie Brooke", level: "infantil" },
    { gb: 15809, title: "A Apple Pie", author: "Kate Greenaway", level: "infantil" },
    { gb: 18155, title: "The Story of the Three Little Pigs", author: "L. Leslie Brooke", level: "infantil" },
    { gb: 23322, title: "The Three Bears", author: "Anonymous", level: "infantil" },
    { gb: 15661, noimages: true, title: "The Golden Goose Book", author: "L. Leslie Brooke", level: "infantil" },
    { ws: "en", title: "The Little Red Hen", author: "Florence White Williams", level: "infantil" },
    { gb: 19994, noimages: true, title: "The Aesop for Children", author: "Aesop", level: "infantil" },
    { gb: 28, title: "The Fables of Aesop", author: "Aesop (Joseph Jacobs)", level: "infantil" },
    { gb: 11339, noimages: true, title: "Aesop's Fables: A New Translation", author: "Aesop (V. S. Vernon Jones)", level: "infantil" },
    { gb: 17208, title: "The Tales of Mother Goose", author: "Charles Perrault", level: "infantil" },
    { gb: 7439, title: "English Fairy Tales", author: "Joseph Jacobs", level: "infantil" },
    { gb: 14642, title: "McGuffey's Eclectic Primer, Revised Edition", author: "William Holmes McGuffey", level: "principiante" },
    { gb: 14640, title: "McGuffey's First Eclectic Reader, Revised Edition", author: "William Holmes McGuffey", level: "principiante" },
    { gb: 1489, title: "The New McGuffey First Reader", author: "William Holmes McGuffey", level: "principiante" },
    { gb: 14668, noimages: true, title: "McGuffey's Second Eclectic Reader", author: "William Holmes McGuffey", level: "principiante" },
    { gb: 14766, title: "McGuffey's Third Eclectic Reader", author: "William Holmes McGuffey", level: "principiante" },
    { gb: 61852, noimages: true, title: "Kittens and Cats: A First Reader", author: "Eulalie Osgood Grover", level: "principiante" },
    { gb: 65323, noimages: true, title: "A First Reader", author: "Frank E. Spaulding and Catherine T. Bryce", level: "principiante" },
    { gb: 19551, noimages: true, title: "Alice in Wonderland, Retold in Words of One Syllable", author: "Lewis Carroll (Mrs. J. C. Gorham)", level: "principiante" },
    { gb: 18442, title: "Fifty Famous Stories Retold", author: "James Baldwin", level: "principiante" },
    { gb: 21, title: "Three Hundred Aesop's Fables", author: "Aesop (George Fyler Townsend)", level: "principiante" },
    { gb: 2781, title: "Just So Stories", author: "Rudyard Kipling", level: "intermedio" },
    { gb: 2591, title: "Grimms' Fairy Tales", author: "Jacob and Wilhelm Grimm", level: "intermedio" },
    { gb: 1597, title: "Andersen's Fairy Tales", author: "H. C. Andersen", level: "intermedio" },
    { gb: 902, noimages: true, title: "The Happy Prince, and Other Tales", author: "Oscar Wilde", level: "intermedio" },
    { ws: "en", title: "The Velveteen Rabbit", author: "Margery Williams", level: "intermedio" },
    { gb: 21286, title: "Mother West Wind \"How\" Stories", author: "Thornton W. Burgess", level: "intermedio" },
    { gb: 503, title: "The Blue Fairy Book", author: "Andrew Lang", level: "intermedio" },
  ],
  it: [
    { ws: "it", title: "Favole di Esopo", author: "Esopo", level: "infantil" },
    { ws: "it", title: "Il libro delle fate", author: "Charles Perrault", level: "infantil" },
    { ws: "it", title: "Cappuccetto Rosso", author: "Charles Perrault", level: "infantil" },
    { ws: "it", title: "Quaranta novelle", author: "Hans Christian Andersen", level: "infantil" },
    { ws: "it", title: "C'era una volta... Fiabe", author: "Luigi Capuana", level: "infantil" },
    { ws: "it", title: "Il raccontafiabe", author: "Luigi Capuana", level: "infantil" },
    { ws: "it", title: "Chi vuol fiabe, chi vuole?", author: "Luigi Capuana", level: "infantil" },
    { ws: "it", title: "La danza degli gnomi e altre fiabe", author: "Guido Gozzano", level: "infantil" },
    { ws: "it", title: "Memorie di un pulcino (1918)", author: "Ida Baccini", level: "infantil" },
    { gb: 17805, noimages: true, title: "Lezioni e Racconti per i bambini", author: "Ida Baccini", level: "infantil" },
    { gb: 69422, noimages: true, title: "Le gaie farandole", author: "Antonio Beltramelli", level: "infantil" },
    { gb: 22503, title: "Piccoli eroi: Libro per i ragazzi", author: "Virginia Treves", level: "infantil" },
    { ws: "it", title: "Favole (Fedro)", author: "Fedro", level: "infantil" },
    { ws: "it", title: "Favole (La Fontaine)", author: "Jean de La Fontaine", level: "infantil" },
    { ws: "it", title: "Storie allegre", author: "Carlo Collodi", level: "infantil" },
    { gb: 52484, noimages: true, title: "Le avventure di Pinocchio: Storia di un burattino", author: "Carlo Collodi", level: "principiante" },
    { gb: 24072, title: "First Italian Readings", author: "Various", level: "principiante" },
    { gb: 49463, title: "Racconti per giovinetti", author: "Pietro Thouar", level: "principiante" },
    { ws: "it", title: "Ciuffettino", author: "Yambo", level: "principiante" },
    { gb: 28371, noimages: true, title: "Le avventure d'Alice nel paese delle meraviglie", author: "Lewis Carroll", level: "principiante" },
    { ws: "it", title: "Cuore (1889)", author: "Edmondo De Amicis", level: "principiante" },
    { ws: "it", title: "Il giornalino di Gian Burrasca", author: "Vamba", level: "principiante" },
    { ws: "it", title: "Le novelle della nonna", author: "Emma Perodi", level: "principiante" },
    { gb: 73094, title: "I ragazzi d'una volta e i ragazzi d'adesso", author: "marchesa Colombi", level: "intermedio" },
    { gb: 61885, title: "Ricordi d'infanzia e di scuola", author: "Edmondo De Amicis", level: "intermedio" },
    { gb: 58341, title: "Novelle", author: "Edmondo De Amicis", level: "intermedio" },
    { gb: 42416, title: "Piccole anime", author: "Matilde Serao", level: "intermedio" },
    { gb: 41342, title: "Piccole storie del mondo grande", author: "Alfredo Panzini", level: "intermedio" },
    { gb: 34519, title: "Mastr'Impicca", author: "Vittorio Imbriani", level: "intermedio" },
    { gb: 65736, title: "Il giro del mondo in ottanta giorni", author: "Jules Verne", level: "intermedio" },
    { gb: 61209, noimages: true, title: "I Robinson italiani", author: "Emilio Salgari", level: "intermedio" },
    { ws: "it", title: "Le tigri di Mompracem", author: "Emilio Salgari", level: "intermedio" },
    { gb: 61179, noimages: true, title: "Viaggi di Gulliver nelle lontane regioni", author: "Jonathan Swift", level: "intermedio" },
    { gb: 54787, title: "Il lampionaio", author: "Maria S. Cummins", level: "intermedio" },
    { ws: "it", title: "L'isola del tesoro", author: "Robert Louis Stevenson", level: "intermedio" },
    { ws: "it", title: "Avventure di Robinson Crusoe", author: "Daniel Defoe", level: "intermedio" },
    { ws: "it", title: "Le Mille ed una Notti", author: "anónimo", level: "intermedio" },
    { ws: "it", title: "Novellino", author: "anónimo", level: "intermedio" },
  ],
  de: [
    { gb: 24571, title: "Der Struwwelpeter", author: "Heinrich Hoffmann", level: "infantil" },
    { gb: 17161, noimages: true, title: "Max und Moritz", author: "Wilhelm Busch", level: "infantil" },
    { gb: 2322, title: "Hans Huckebein", author: "Wilhelm Busch", level: "infantil" },
    { gb: 32034, title: "König Nußknacker und der arme Reinhold", author: "Heinrich Hoffmann", level: "infantil" },
    { gb: 57412, title: "Etwas von den Wurzelkindern", author: "Sibylle von Olfers", level: "infantil" },
    { gb: 70178, title: "Ri-Ra-Rutsch: Alte und neue Kinderreime", author: "varios", level: "infantil" },
    { ws: "de", title: "Der Froschkönig oder der eiserne Heinrich (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Hänsel und Grethel (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Rothkäppchen (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Die Bremer Stadtmusikanten (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Sneewittchen (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Aschenputtel (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Dornröschen (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Rumpelstilzchen (1857)", author: "Brüder Grimm", level: "infantil" },
    { ws: "de", title: "Der Struwwelpeter", author: "Heinrich Hoffmann", level: "infantil" },
    { ws: "de", title: "Max und Moritz", author: "Wilhelm Busch", level: "infantil" },
    { gb: 77905, noimages: true, title: "Deutsche Märchen gesammelt durch die Brüder Grimm", author: "Brüder Grimm", level: "infantil" },
    { gb: 23787, title: "Märchen-Sammlung", author: "anónimo", level: "infantil" },
    { gb: 42900, title: "Gänsemütterchens Märchen", author: "Charles Perrault", level: "infantil" },
    { gb: 19163, title: "Märchen für Kinder", author: "H. C. Andersen", level: "infantil" },
    { gb: 50965, title: "Märchen (Die Nachtigall, Die kleine Seejungfrau, Der Reisekamerad)", author: "H. C. Andersen", level: "infantil" },
    { gb: 63465, noimages: true, title: "Ludwig Bechsteins Märchenbuch", author: "Ludwig Bechstein", level: "infantil" },
    { gb: 8917, title: "Von Kindern und Katzen, und wie sie die Nine begruben", author: "Theodor Storm", level: "infantil" },
    { gb: 22413, title: "Alaeddin und die Wunderlampe", author: "Curt Moreck", level: "infantil" },
    { gb: 8923, title: "Die Regentrude", author: "Theodor Storm", level: "infantil" },
    { gb: 35794, title: "Märchen und Erzählungen für Anfänger. Erster Teil", author: "H. A. Guerber", level: "principiante" },
    { gb: 45189, title: "Märchen und Erzählungen für Anfänger. Zweiter Teil", author: "H. A. Guerber", level: "principiante" },
    { gb: 8392, title: "Hin und Her: Ein Buch für die Kinder", author: "Henry H. Fick", level: "principiante" },
    { gb: 49503, title: "Ährenlese: A German Reader with Practical Exercises", author: "varios", level: "principiante" },
    { gb: 9375, title: "Ausgewählte Fabeln", author: "Gotthold Ephraim Lessing", level: "principiante" },
    { gb: 9158, title: "Fabeln und Erzählungen", author: "Gotthold Ephraim Lessing", level: "principiante" },
    { ws: "de", title: "Schatzkästlein des rheinischen Hausfreundes", author: "Johann Peter Hebel", level: "principiante" },
    { gb: 58300, title: "Das erste Schuljahr", author: "Agnes Sapper", level: "principiante" },
    { gb: 58989, title: "Tiere und Pflanzen in Wald und Feld", author: "Arabella B. Buckley", level: "principiante" },
    { gb: 9860, title: "Moni der Geißbub", author: "Johanna Spyri", level: "principiante" },
    { gb: 7500, title: "Heidis Lehr- und Wanderjahre", author: "Johanna Spyri", level: "intermedio" },
    { gb: 7512, title: "Heidi kann brauchen, was es gelernt hat", author: "Johanna Spyri", level: "intermedio" },
    { gb: 21021, title: "Die Biene Maja und ihre Abenteuer", author: "Waldemar Bonsels", level: "intermedio" },
    { gb: 6638, title: "Märchen-Almanach auf das Jahr 1826 (Die Karawane)", author: "Wilhelm Hauff", level: "intermedio" },
    { gb: 6639, title: "Märchen-Almanach auf das Jahr 1827 (Der Zwerg Nase)", author: "Wilhelm Hauff", level: "intermedio" },
    { gb: 6640, title: "Märchen-Almanach auf das Jahr 1828 (Das kalte Herz)", author: "Wilhelm Hauff", level: "intermedio" },
    { ws: "de", title: "Die Geschichte von Kalif Storch", author: "Wilhelm Hauff", level: "intermedio" },
    { ws: "de", title: "Der Zwerg Nase", author: "Wilhelm Hauff", level: "intermedio" },
    { gb: 31114, title: "Wunderbare Reise des kleinen Nils Holgersson mit den Wildgänsen", author: "Selma Lagerlöf", level: "intermedio" },
    { gb: 19778, title: "Alice's Abenteuer im Wunderland", author: "Lewis Carroll", level: "intermedio" },
    { gb: 36813, title: "Kasperle auf Reisen", author: "Josephine Siebe", level: "intermedio" },
    { gb: 49738, title: "Neue Kindergeschichten aus Oberheudorf", author: "Josephine Siebe", level: "intermedio" },
    { gb: 31309, title: "Der Trotzkopf", author: "Emmy von Rhoden", level: "intermedio" },
  ],
  ar: [
    { ws: "ar", title: "رابونزيل", author: "الأخوان غريم", level: "infantil" },
    { ws: "ar", title: "سندريلا", author: "الأخوان غريم", level: "infantil" },
    { ws: "ar", title: "طفلة مريم", author: "الأخوان غريم", level: "infantil" },
    { ws: "ar", title: "مجلة الرسالة/العدد 532/من شعر الأطفال", author: "مجلة الرسالة", level: "infantil" },
    { ws: "ar", title: "مجلة الرسالة/العدد 590/من شعر الأطفال", author: "علي متولي صلاح", level: "infantil" },
    { ws: "ar", title: "مجلة الرسالة/العدد 594/من شعر الأطفال:", author: "علي متولي صلاح", level: "infantil" },
    { ws: "ar", title: "مدينتي", author: "مجهول", level: "infantil" },
    { ws: "ar", title: "حكاية الكلب مع الحمامه", author: "أحمد شوقي", level: "infantil" },
    { ws: "ar", title: "مجلة الرسالة/العدد 49/المارد الأناني", author: "أوسكار وايلد", level: "principiante" },
    { ws: "ar", title: "حكاية الشتاء (لام)", author: "تشارلز ومريم لام", level: "principiante" },
    { ws: "ar", title: "قصة ساعة", author: "كيت شوبان", level: "principiante" },
    { ws: "ar", title: "ندم", author: "كيت شوبان", level: "principiante" },
    { ws: "ar", title: "الطفولتان", author: "مصطفى صادق الرافعي", level: "intermedio" },
    { ws: "ar", title: "اليمامتان", author: "مصطفى صادق الرافعي", level: "intermedio" },
    { ws: "ar", title: "في الربيع الأزرق", author: "مصطفى صادق الرافعي", level: "intermedio" },
    { ws: "ar", title: "أيها البحر", author: "مصطفى صادق الرافعي", level: "intermedio" },
    { ws: "ar", title: "ضحاك", author: "الفردوسي (ترجمة البنداري)", level: "intermedio" },
    { ws: "ar", title: "الشاهنامة/أفريدون", author: "الفردوسي (ترجمة البنداري)", level: "intermedio" },
    { ws: "ar", title: "سهراب", author: "الفردوسي (ترجمة البنداري)", level: "intermedio" },
    { ws: "ar", title: "مغامرات حاجي بابا الإصفهاني", author: "جيمس موريير", level: "intermedio" },
    { ws: "ar", title: "الزير سالم", author: "مجهول", level: "intermedio" },
    { ws: "ar", title: "مجلة الرسالة/العدد 824/القصص", author: "غي دي موباسان", level: "intermedio" },
  ],
  zh: [
    { ws: "zh", title: "鵝媽媽的故事 (戴望舒譯)", author: "Charles Perrault, trad. 戴望舒", level: "infantil" },
    { gb: 67976, title: "故事新讀本: 第一冊", author: "anónimo (上海大東書局)", level: "principiante" },
    { gb: 12479, title: "三字經", author: "anónimo (atrib. 王應麟)", level: "principiante" },
    { ws: "zh", title: "弟子規", author: "李毓秀", level: "principiante" },
    { ws: "zh", title: "百家姓", author: "anónimo", level: "principiante" },
    { ws: "zh", title: "神童詩", author: "汪洙", level: "principiante" },
    { ws: "zh", title: "訓蒙幼學詩", author: "anónimo", level: "principiante" },
    { ws: "zh", title: "千家詩", author: "劉克莊, 謝枋得, 王相 (comp.)", level: "principiante" },
    { ws: "zh", title: "重訂三字經", author: "王應麟, rev. 章太炎", level: "principiante" },
    { ws: "zh", title: "一件小事", author: "魯迅", level: "principiante" },
    { gb: 23823, title: "弟子規", author: "李毓秀", level: "principiante" },
    { gb: 25196, title: "百家姓", author: "anónimo", level: "principiante" },
    { ws: "zh", title: "增廣昔時賢文", author: "anónimo", level: "intermedio" },
    { ws: "zh", title: "名賢集", author: "anónimo", level: "intermedio" },
    { ws: "zh", title: "朱子家訓", author: "朱用純", level: "intermedio" },
    { ws: "zh", title: "小學韻語", author: "anónimo", level: "intermedio" },
    { ws: "zh", title: "今文孝經", author: "anónimo", level: "intermedio" },
    { ws: "zh", title: "千字文", author: "周興嗣", level: "intermedio" },
    { ws: "zh", title: "聲律啓蒙", author: "車萬育", level: "intermedio" },
    { ws: "zh", title: "愛的教育", author: "Edmondo De Amicis, trad. 夏丏尊", level: "intermedio" },
    { ws: "zh", title: "兔和貓", author: "魯迅", level: "intermedio" },
    { ws: "zh", title: "鴨的喜劇", author: "魯迅", level: "intermedio" },
    { ws: "zh", title: "風箏", author: "魯迅", level: "intermedio" },
    { ws: "zh", title: "好的故事", author: "魯迅", level: "intermedio" },
    { ws: "zh", title: "頭髮的故事", author: "魯迅", level: "intermedio" },
    { ws: "zh", title: "故鄉", author: "魯迅", level: "intermedio" },
    { ws: "zh", title: "社戲", author: "魯迅", level: "intermedio" },
    { ws: "zh", title: "俄羅斯的童話", author: "Maksim Gorki, trad. 魯迅", level: "intermedio" },
    { ws: "zh", title: "伊娑菩喻言", author: "Esopo, trad. Robert Thom", level: "intermedio" },
    { ws: "zh", title: "唐詩三百首", author: "孫洙 (comp.)", level: "intermedio" },
    { ws: "zh", title: "笑林廣記", author: "游戲主人", level: "intermedio" },
    { gb: 24184, title: "千字文", author: "周興嗣", level: "intermedio" },
    { gb: 23816, title: "朱子治家格言", author: "朱用純", level: "intermedio" },
    { gb: 24232, title: "孝經", author: "anónimo", level: "intermedio" },
    { gb: 52269, title: "幼學瓊林", author: "程允升", level: "intermedio" },
    { ws: "zh", title: "龍文鞭影", author: "蕭良有", level: "intermedio" },
    { ws: "zh", title: "伊索寓言 (林紓)", author: "Esopo, trad. 林紓", level: "intermedio" },
  ],
};
